[package]
name = "strlen"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "strlen"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.30.0"
unicode-segmentation = "1.10.1"